### ISSUE TITLE
Github Actions to check for duplicate entries

### ISSUE THREAD

**Issue by codingo** [disclose/diodb#202]
#196 introduced a double up of each entry that wasn't caught in review. In order to prevent repeat cases of  this, or minor double ups, a Github actions entry should be created that checks for any double ups of the program name at the time when a new pull request is created, and if so, fail the case.

**Comment by yesnet0** [comment]
@prodigysml Any update on this?

**Comment by prodigysml** [comment]
NGL, totally forgot about it @yesnet0. Working on it rn!
