### ISSUE TITLE
Track security.txt: proposed standard for defining security policies

### ISSUE THREAD

**Issue by nealmcb** [disclose/diodb#222]
An Internet Draft, [security.txt: Proposed standard for defining security policies](https://securitytxt.org/) (e.g. [draft 09, February 25, 2020](https://tools.ietf.org/html/draft-foudil-securitytxt-09)), is wending its way thru the IETF that is related to the goals of this repository. Feedback from this community should be welcome.

If it is released as an RFC, it should be noted here in documentation and examples and perhaps a schema update.

**Comment by yesnet0** [comment]
Hi @nealmcb - There is a parallel activity to integrate security.txt into both the disclose.io list/repo, and to provide feedback towards the security.txt project as well

**Comment by yesnet0** [comment]
Hi @nealmcb - An update to this project is here: https://github.com/disclose/diosts
