### ISSUE TITLE
[US Election] Leased/Rented voting equipment scope question

### ISSUE THREAD

**Issue by JLLeitschuh** [disclose/diodb#223]
> Out-of-scope systems include infrastructure or other equipment not owned by participating state agencies and their county and local subdivisions. It is the responsibility of vulnerability researchers, testers, or others seeking to comply with this policy to ensure the equipment or system is not out-of-scope.

What about systems that are leased/rented? Can these systems not be considered in-scope?

> Financing options. In addition to an outright purchase, vendors may offer lease options to jurisdictions looking to acquire a new system.
> \- https://www.ncsl.org/research/elections-and-campaigns/voting-equipment.aspx

What would program runners need to do to include leased equipment in scope?

**Comment by cablej** [comment]
I would assume that the same provisions for software not owned by states/local entities would apply to leased systems. Security researchers would need authorization from the system owner/vendor in order to test those systems.

**Comment by JLLeitschuh** [comment]
> Security researchers would need authorization from the system owner/vendor in order to test those systems.

Why is this the responsibility of the security researcher? Why is it not the responsibility of the program runner to do this?
