### ISSUE TITLE
Duplicate entries for `Australia Post` responsible disclosure policy

### ISSUE THREAD

**Issue by bugbaba** [disclose/diodb#249]
Hi Team,

The responsible disclosure policy of `Australia Post` is mention twice in the list.

- https://github.com/disclose/diodb/blob/master/program-list/program-list.json#L24
- https://github.com/disclose/diodb/blob/master/program-list/program-list.json#L805

--
Regards,
@bugbaba

**Comment by yesnet0** [comment]
Thanks @bugbaba! Would you mind submitting a PR to remove the duplicate entry?

**Comment by yesnet0** [comment]
Fixed!
