### ISSUE TITLE
Relaso program's bug_bounty is set to true, But there policy specifies they don't

### ISSUE THREAD

**Issue by bugbaba** [disclose/diodb#250]
Hi Team,

The `bug_bounty` value is set to `true` for Relaso, But as per there policy page they don't give out bounties.

![image](https://user-images.githubusercontent.com/29960776/95783290-2e64b100-0cef-11eb-8bfa-568d5aaa29f1.png)

https://github.com/disclose/diodb/blob/master/program-list/program-list.json#L6855

--
Regards,
@bugbaba

**Comment by yesnet0** [comment]
Thanks @bugbaba. Would you be able to submit a PR to the json file that reflects this?

**Comment by yesnet0** [comment]
Fixed!
