### ISSUE TITLE
Update https://github.com/disclose/diodb/blob/master/program-list/program-list-schema.json to reflect new data schema

### ISSUE THREAD

**Issue by yesnet0** [disclose/diodb#252]
field | required | type | options | source/s | description
-- | -- | -- | -- | -- | --
program_name | no | string | name | pr | The commonly used name for the program.
policy_url | yes | string | url | security.txt, pr | The URL referring to the official public policy.
contact_url | yes | string | url, mailto | security.txt, pr | The official communication channel for the program as defined by the policy.
launch_date | no | date | date | pr | The date of program launch.
offers_bounty | no | enum | yes, no, partial | pr | Does the policy state that the program offers a cash or cash-equivalent reward?
offers_swag | no | boolean | yes, no | pr | Does the policy state that the program offers a non-cash reward or token of thanks?
hall_of_fame | no | string | url | security.txt, pr | The URL of the hall of fame for the program. NULL if none are present.
safe_harbor | no | enum | full, partial, none | pr | The safe harbor status of the program according to the definitions at https://disclose.io
public_disclosure | yes | enum | nda, discretionary, co-ordinated, NULL | pr | The public disclosure policy as stated in the program policy. NULL if none are present.
disclosure_timeline_days | no(yes if public_disclosure = co-ordinated) | int(unsigned) | number | pr | If the program uses a proactive policy, the agreed number of days between submission of a vulnerability and publicly disclosure of the vulnerability.
pgp_key | no | string | url | security.txt, pr | The URL to the PGP in-use for encrypting submissions. NULL if none are present.
hiring | no | string | url | security.txt, pr |  
securitytxt_url | no | string | url | security.txt, pr |  
preferred_languages | no | string | text | security.txt |

**Comment by prodigysml** [comment]
Is the program name supposed to be required @yesnet0 ? Happy to remove its required entry, but I think it might be a good idea to keep it.

**Comment by prodigysml** [comment]
After talking to @yesnet0, it is likely best to make `program_name` into `not required` and defaulting to NULL. For sorting the dataset, we will sort alphabetically (not ASCII, so you will need to do `str.lower`) by the `program_name` and then the `policy_url`.
