### ISSUE TITLE
Making it easier for non-Github users to update diodb

### ISSUE THREAD

**Issue by yesnet0** [disclose/diodb#300]
As someone who has an addition or change to make to diodb but is not conversant with git or Github (e.g. legal team, marketing team, executive, etc) I would like to be able to use a web-based form to submit a change.

As a maintainer, I'd like submissions from the form above to be checked against the existing database to determine whether they are a new entry or an update. Given the user isn't a git native, I also presume they might have trouble with json and don't assume they've been able to do this check themselves. 

Conceptually: Web form -> json -> Duplicate check action -> PR creation action -> PR created

**Comment by sickcodes** [comment]
I'll assist!

**Comment by yesnet0** [comment]
Thanks @sickcodes!

**Comment by yesnet0** [comment]
@sickcodes Checking in on this... how were you thinking of approaching it?
