### ISSUE TITLE
Ingest/merge CISAs Federal Gov VDP register

### ISSUE THREAD

**Issue by yesnet0** [disclose/diodb#307]
CISA have stood up a VDP register for all Federal agencies running VDPs under BOD 20-01: https://github.com/cisagov/vdp-in-fceb. This should be merged with diodb on a one-time basis, and it'd be good to look at ways to keep that repo in sync going forward.

**Comment by sickcodes** [comment]
Want me to write a shell script? `markdown table` -> `json`?

**Comment by yesnet0** [comment]
@sickcodes For sure!

**Comment by yesnet0** [comment]
Solved in https://github.com/disclose/diodb/pull/309 by @0ddInput.
