### ISSUE TITLE
Diodb front end only works in landscape mode on mobile

### ISSUE THREAD

**Issue by sickcodes** [disclose/diodb#311]
@AndrewMohawk hey mate, can you check if this works on mobile in portrait mode? I can't see unless I swing the phone into landscape currently

__Originally posted by @sickcodes in https://github.com/disclose/docs/pull/1#issuecomment-808681164__

![image](https://user-images.githubusercontent.com/65906298/112714079-7c055c80-8ed0-11eb-8c92-93a9b5ed8af4.jpeg)

**Comment by yesnet0** [comment]
Fixed by @andrewmohawk in https://github.com/disclose/docs/pull/3
