### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by JLLeitschuh** [disclose/diodb#356]
Currently, the search is broken:

https://disclose.io/programs/

I'm seeing the following error in the console:
```
An error has occurred.                                                programs-datatable-standalone.html:273
```

**Comment by sickcodes** [comment]
Fixed https://github.com/disclose/diodb/commit/a66a65865a577ce9c9f30a4f8ced659ca2ceb6a7

**Comment by sickcodes** [comment]
There was an actual merge conflict merged, all sorted.
