### ISSUE TITLE
Footer social media link need to be fix and stale Copyrights

### ISSUE THREAD

**Issue by mbiesiad** [disclose/diodb#402]
Hi,

Repro steps:
1. Go to https://disclose.io/ or https://disclose.io/programs/
2. Scroll down to see footer

At this moment for LinkedIn icon there, social media link is for Facebook (so, doubled).
https://www.facebook.com/disclose-io and https://www.facebook.com/discloseio
Moreover, we can see "Copyright 2018-2022".

Screenshot:
![image](https://user-images.githubusercontent.com/18367606/224292392-cd2bb75a-9ede-426d-ba6d-e1c9fa98cceb.png)

Proposed solutions:
For LinkedIn icon add proper link - change from Facebook.
Change "Copyright 2018-2022" to "2018-2023"

Best wishes,

**Comment by yesnet0** [comment]
Many thanks!
