### ISSUE TITLE
Plisio BugBounty

### ISSUE THREAD

**Issue by AdPlisio** [disclose/diodb#403]
Hello

Plisio is committed to providing a secure environment for its users. While our IT specialists work diligently to identify any potential security issues, it's always possible that some may be missed.

As a result, we have launched a bug bounty program that enables all Plisio users to earn rewards for helping find code vulnerabilities.

https://plisio.net/bug-bounty

**Comment by nikitastupin** [comment]
Hey @AdPlisio!

Thanks for notifying us about the program. I've added it at the 07f8414 commit.
