### ISSUE TITLE
add new program: Grafana Labs

### ISSUE THREAD

**Issue by KristianGrafana** [disclose/diodb#410]
### URL

https://github.com/grafana/bugbounty/blob/main/README.md

### Contact

https://github.com/grafana/bugbounty

### Bounty

Yes

### Additional Information

Let me know if you need any additional details!

**Comment by nikitastupin** [comment]
Hi @KristianGrafana,

Thank you for opening the issue! The program is already in the list :) https://github.com/disclose/diodb/blob/54667185e750ea6e115add7625749a55a1b96dc5/program-list.json#L8510-L8525

Feel free to reopen the issue if needed!
