### ISSUE TITLE
https://liveclicker.com/trust/report-a-vulnerability/ Looks like there is no way to submit a vulnerability

### ISSUE THREAD

**Issue by zcvfvdfbfggn** [disclose/diodb#412]
![9 F4X4QM`VXH7CO1}HIEOFK](https://github.com/disclose/diodb/assets/113565019/64cb6c66-ff35-4d2f-99d5-2a00a9eaa59b)

**Comment by nikitastupin** [comment]
Did you try the submission form down the page?

<img width="1624" alt="image" src="https://github.com/disclose/diodb/assets/18281368/bf6a4407-67a2-49ca-99d3-cb7dd6407ee9">

**Comment by zcvfvdfbfggn** [comment]
yes,can't use

**Comment by nikitastupin** [comment]
Hmm, that's strange. I haven't tried the form but it may be an issue with the program page or BugCrowd. Anyways, I'm inclined towards leaving it as it is on diodb's side. I think it makes sense to contact the program about the issue. Thanks!
