### ISSUE TITLE
add new program: inDrive

### ISSUE THREAD

**Issue by sapielsam** [disclose/diodb#413]
### URL

https://hackerone.com/indrive

### Contact

https://hackerone.com/indrive/reports/new?type=team&report_type=vulnerability

### Bounty

Yes

### Additional Information

https://t.me/indrive_bbp - the official inDrive Bug Bounty Updates channel! Here you'll find all the latest news and updates about our Bug Bounty. We are happy to share with you information about the launch of new services, features, promotions and other information

**Comment by nikitastupin** [comment]
Hi! Thank you for raising this. I've added the program in https://github.com/disclose/diodb/commit/965ca3cdc1d64b297f976cfb9d279ce549ffc178.
