### ISSUE TITLE
Brentley Systems Responsible disclosure program

### ISSUE THREAD

**Issue by DanielGurevich1** [disclose/diodb#416]
### URL

https://www.bentley.com/legal/bug-bounty-report/

### Contact

https://www.bentley.com/legal/bug-bounty-report/

### Bounty

Yes

### Additional Information

At Bentley Systems, we take the security of our systems and products seriously, and we value the security community. The disclosure of security vulnerabilities helps us ensure the security and privacy of our users.

**Comment by nikitastupin** [comment]
Thank you! Added in https://github.com/disclose/diodb/commit/a311ba602bf5ec1713e3bce43b9ace09cc39efc0
