### ISSUE TITLE
add new program: Livesport

### ISSUE THREAD

**Issue by jiribartusek-ls** [disclose/diodb#429]
### URL

https://bugbounty.livesport.eu/

### Contact

https://bugbounty.livesport.eu/#report

### Bounty

Yes

### Additional Information

Vuln Disclosure Policy: https://bugbounty.livesport.eu/docs/Vulnerability%20Disclosure%20Policy.pdf
Safe harbor implemented
The bug bounty program applies to Livesport's projects, such as flashscore.com, livesport.cz, diretta.it etc.

**Comment by nikitastupin** [comment]
I've added in https://github.com/disclose/diodb/commit/bacd4e1979ff953c5dd93d5be7b397f2784f044e. Thank you for your contribution!
