### ISSUE TITLE
Update Dell Bug Bounty Program Link

### ISSUE THREAD

**Issue by peakyblinder2395** [disclose/diodb#433]
Current Link is pointing to a blank page: https://bugcrowd.com/dell

If you can add two entries for Dell:
Dell Application: https://bugcrowd.com/dell-com
Dell Product: https://bugcrowd.com/dell-product

Thank you!

**Comment by nikitastupin** [comment]
Updated at https://github.com/disclose/diodb/commit/7908715ba151931cbdf7d0e0ca84f4f66b02ff52. Thank you!!
